#include "input_hooks.h"
#include "cp_state_manager.h"
#include <iostream>

namespace Jugnu
{
    std::atomic<DWORD> g_lastKeyboardInputMs{0};
    std::atomic<DWORD> g_lastMouseInputMs{0};
    std::atomic<bool>  g_isMouseOnly{false};
    std::atomic<int>   g_cpKeyStrokeCount{0};

    static HHOOK s_kbHook = nullptr;
    static HHOOK s_mseHook = nullptr;
    static HANDLE s_hookThreadHandle = nullptr;
    static DWORD s_hookThreadId = 0;

    static LRESULT CALLBACK KbProc(int nCode, WPARAM wParam, LPARAM lParam)
    {
        if(nCode >= 0 && (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN))
        {
            KBDLLHOOKSTRUCT* pKeyBoard = (KBDLLHOOKSTRUCT*)lParam;
            // Ignore synthetic inputs generated by SendInput (e.g. GhostClipboard)
            if((pKeyBoard->flags & LLKHF_INJECTED) == 0)
            {
                g_lastKeyboardInputMs = GetTickCount();
                g_isMouseOnly = false;
                g_cpKeyStrokeCount++;

                // Notify state manager immediately (zero latency)
                CPStateManager::OnKeyDown();
            }
        }
        return CallNextHookEx(s_kbHook, nCode, wParam, lParam);
    }

    static LRESULT CALLBACK MouseProc(int nCode, WPARAM wParam, LPARAM lParam)
    {
        if(nCode >= 0)
        {
            MSLLHOOKSTRUCT* pMouse = (MSLLHOOKSTRUCT*)lParam;
            // Ignore synthetic inputs generated by SendInput
            if((pMouse->flags & LLMHF_INJECTED) == 0)
            {
                g_lastMouseInputMs = GetTickCount();

                // If mouse is moving but keyboard has been idle for 2s, flag as mouse-only
                if(GetTickCount() - g_lastKeyboardInputMs > 2000) g_isMouseOnly = true;
            }
        }
        return CallNextHookEx(s_mseHook, nCode, wParam, lParam);
    }

    static DWORD WINAPI HookThreadProc(LPVOID)
    {
        s_kbHook = SetWindowsHookEx(WH_KEYBOARD_LL, KbProc, GetModuleHandle(NULL), 0);
        s_mseHook = SetWindowsHookEx(WH_MOUSE_LL, MouseProc, GetModuleHandle(NULL), 0);

        if(!s_kbHook || !s_mseHook)
        {
            std::cerr << "\033[1;31m[InputHooks]\033[0m Failed to install hooks.\n";
            return 1;
        }

        std::cout << "\033[1;32m[InputHooks]\033[0m CP hooks installed and pumping on dedicated thread.\n";

        MSG msg;
        // This loop blocks until a message arrives, using 0% CPU while idle
        while(GetMessage(&msg, NULL, 0, 0) > 0)
        {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }

        if(s_kbHook) UnhookWindowsHookEx(s_kbHook);
        if(s_mseHook) UnhookWindowsHookEx(s_mseHook);

        s_kbHook = nullptr;
        s_mseHook = nullptr;

        std::cout << "\033[1;33m[InputHooks]\033[0m CP hooks removed.\n";
        return 0;
    }

    void StartCPInputHooks()
    {
        if(s_hookThreadHandle) return;  // already running
        g_cpKeyStrokeCount = 0;
        g_lastKeyboardInputMs = GetTickCount();
        g_lastMouseInputMs = GetTickCount();
        g_isMouseOnly = false;

        s_hookThreadHandle = CreateThread(NULL, 0, HookThreadProc, NULL, 0, &s_hookThreadId);
    }

    void StopCPInputHooks()
    {
        if (s_hookThreadHandle && s_hookThreadId)
        {
            // Send WM_QUIT to break the GetMessage loop cleanly
            PostThreadMessage(s_hookThreadId, WM_QUIT, 0, 0);
            WaitForSingleObject(s_hookThreadHandle, 1000);
            CloseHandle(s_hookThreadHandle);
            s_hookThreadHandle = nullptr;
            s_hookThreadId = 0;
        }
    }
}